export const GET_COMMANDS_LOAD = "GET_COMMANDS_LOAD";
export const GET_COMMANDS_FAIL = "GET_COMMANDS_FAIL";
export const GET_COMMANDS_SUCCESS = "GET_COMMANDS_SUCCESS";
export const GET_COMMAND = "GET_COMMAND";


export const EDIT_FALSE = "EDIT_FALSE";
export const EDIT_TRUE= "EDIT_TRUE";
